---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-http
  labels:
    app: acmeair
    tier: monolithic
  namespace: acmeair
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9080
      targetPort: 9080
  selector:
    app: acmeair
    tier: monolithic
---
apiVersion: v1
kind: Service
metadata:
  name: acmeair-https
  labels:
    app: acmeair
    tier: monolithic
  namespace: acmeair
spec:
  ports:
    - name: https
      protocol: TCP
      port: 9443
      targetPort: 9443
  selector:
    app: acmeair
    tier: monolithic
