apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: acmeair
  namespace: acmeair

generatorOptions:
  disableNameSuffixHash: true

resources:
- 0_project.yaml
- 2_service.yaml
- 3_route.yaml
- 4_autoscaler.yaml
- 8_db_service.yaml
- db-config-secret.yaml

sortOptions:
    order: fifo

secretGenerator:
- name: mongodb-creds
  envs:
  - env.secret
