apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: acmeair
  namespace: acmeair

generatorOptions:
  disableNameSuffixHash: true

resources:
- project.yaml
- service.yaml
- route.yaml
- autoscaler.yaml
- db-service.yaml
- db-config-secret.yaml

sortOptions:
    order: fifo

secretGenerator:
- name: mongodb-creds
  envs:
  - env.secret
