apiVersion: v1
kind: Secret
metadata:
  name: mongodb-config
type: Opaque
stringData:
  acmeair.sh: |
    #!/bin/bash
    set -e

    cat << EOF | /usr/bin/mongo -u "$MONGO_INITDB_ROOT_USERNAME" -p "$MONGO_INITDB_ROOT_PASSWORD"
      use acmeair
      db.createCollection("power-coll")
      db.acmeair.insertOne({
        "message": "Database created."
        })

      db.createUser({ 
        "user": "$MONGO_INITDB_ROOT_USERNAME",
        "pwd": "$MONGO_INITDB_ROOT_PASSWORD",
        "roles": [
          { "role": "clusterAdmin", "db": "admin" },
          { "role": "readAnyDatabase", "db": "admin" },
          "readWrite"
        ],
        "mechanisms": [ "SCRAM-SHA-1" ],
        })
    EOF