apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: acmeair 
namespace: acmeair

resources:
- ../../base
- app.yaml
- db.yaml

sortOptions:
   order: fifo

images:
- name: quay.io/pbastide_rh/openshift-demo:acme-air-414
  newName: quay.io/pbastide_rh/openshift-demo  
  newTag: acme-air-414 
